#!/usr/bin/env bash
# MHMuser
# Copyright (C) 2021-2022 DevMHM
#
# This file is a part of < https://github.com/Dev-MHM/MHMuser/ >
# PLease read the GNU Affero General Public License in <https://www.github.com/MHMuser/MHMuser/blob/main/LICENSE/>.

bash resources/session/session.sh
