blank_issues_enabled: true
contact_links:
  - name: MHMsupport
    url: https://t.me/MHMuser
    about: Please drop your doubts or queries there for an immediate response.
  - name: Documentation
    url: https://MHMsupport/
    about: Basic documentation for setting up.